### ISSUE TITLE
Support OWL for Exchange

### ISSUE THREAD

**Issue by marco-brandizi** [protz/Manually-Sort-Folders#103]
Similarly to #46, [OWL for Exchange](https://www.beonex.com/owl/) isn't recognised by this useful plug-in and I don't see my OWA account in the list of sortable accounts. 

Please, could you add support for it? It looks like you just need to add an entry to an enum. Thanks in advance!

**Comment by jfrank14** [comment]
+1 for this. I was just forced to upgrade to Exchange and thus OWL and I can't get my primary mailbox on top where I want it. Changing the prefs.js file doesn't seem to work either.

**Comment by ASchaidler** [comment]
I just had to get OWL for a new company I'm consulting to,  and the OWL MS Exchange email account is at the very *bottom* of my list of emails and will *not* move.  Manually Sort works on every other email account I have, except this darn OWL MD Exchange account.  Not happy I have to use the OWL add-on instead of Exquilla add-on, but Exquilla doesn't seem to be an option any longer with MSExchange and therefore I'm stuck with my new email account at the very bottom of my un-sortable folders.  HELP
<img width="660" alt="Screen Shot 2020-06-29 at 10 10 55 AM" src="https://user-images.githubusercontent.com/67595083/86023099-d8465900-b9f0-11ea-84c2-06de65c6e399.png">

**Comment by Lightfire228** [comment]
Created a PR for this
#122

**Comment by protz** [comment]
Update: Thunderbird developers have committed to allowing sorting accounts (not folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows arbitrary reordering of accounts, meaning that this bug will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.

**Comment by skjerns** [comment]
Unfortunately the feature is still not included and being put back (once again) by the Thunderbird devs :(

Strangely enough I can set the OWL/exchange-account as "default account" within manually sort folders, and that works, but it's not showing up in the "sort accounts" list

**Comment by Lightfire228** [comment]
@skjerns [Here's a build with my PR](https://github.com/protz/Manually-Sort-Folders/files/6044339/Manually-Sort-Folders_2.0.4-owl.xpi.zip) (remove the `.zip` file extension, github doesn't allow file uploads with `.xpi` )

Once you get your accounts sorted how you want, you won't need the owl-specific build, and it should auto-update just fine
