### ISSUE TITLE
Cannot move RSS folder at all

### ISSUE THREAD

**Issue by schneeschmelze** [protz/Manually-Sort-Folders#104]
I have set up an all new RSS folder with some feeds, and I cannot move it at all within my list of folders and accounts. When I put it next to the main mail account this order is shown within the Manually Sort Folders pane, but nothing changes in the folder pane within Thunderbird, no changes even after restart.

Manually sort folders 2.0.2 in Thunderbird 68.2.0 under macOS 10.13.6.

**Comment by hvdkamer** [comment]
For years this add-on worked and the last two years on Debian Stretch. Yesterday I was forced to upgrade to Thunderbird 68.2.2 and this add-on was disabled. Removed it and installed the latest version. I can sort folders in accounts as before. However it is not possible to sort the News -- with RSS feeds -- before the mail accounts. Whatever I do the order becomes mail, local folders and then the News.

I've experimented with changing prefs.js but this doesn't help. Probably because I don't exactly understand the structure? It is a bit complex because I've a lot of subfolders...

Hope this can be fixed, because News at the bottom is pretty useless. Don't understand why Thunderbird developers think this is what people want :-(

**Comment by Moongazer** [comment]
Same here, my Ubuntu updated to Thunderbird 68.2.1 few days ago and since than the RSS newsfeed folder is at the bottom, below my 10+ mail accounts (which is really annoying!!!). So I tried to re-order the folders, but it works only for the mail-accounts, not for the RSS folder (in the settings it shows up on top, but after Thunderbird restarts it stays at the bottom). Changing the "Default folder" setting does not have any effect either.
I'd highly appreciate a fix - or is there any other Addon for this which is working?

**Comment by jeremymeyers** [comment]
On latest 64-bit version on win10, can confirm this is happening here too.

**Comment by protz** [comment]
I'm closing this in favor of #101 -- it requires work on the Thunderbird side (see https://bugzilla.mozilla.org/show_bug.cgi?id=1359410) and I'll post updates in #101 as soon as I make progress. Thanks.
