### ISSUE TITLE
RSS feed always at the bottom

### ISSUE THREAD

**Issue by oscar-h64** [protz/Manually-Sort-Folders#139]
I have 3 email accounts, and an RSS feed. I can re-arrange the 3 email accounts fine with this extension, but no matter where I put the RSS feed in the list it is always at the very bottom below "Local Folders". Setting the RSS feed as the default folder works fine. I'm using Thunderbird 78.6.1 with version 2.0.5 on Arch Linux.

I can't see anything in the console indicating why this is failing - please let me know what other information you need

**Comment by jeremymeyers** [comment]
This is a known bug in Thunderbird that is being worked on on their side.

**Comment by itagagaki** [comment]
@oscar-h64 
Thunderbird version 91 may have solved the issue, have you tried that?
It also allows you to sort the accounts in Account Settings UI.
Thus, you no longer need to use this add-on to sort your accounts, but you can continue to use it to sort your folders, etc.
This add-on has also been updated to version 2.1.0, so please update it if you like and let me know the result.
Because I want to close this issue.

**Comment by oscar-h64** [comment]
Thunderbird 91 does exactly what I need rearranging accounts wise, thanks.

Have also tested rearranging the accounts using this extension v2.1.0 in Thunderbird 91, and that works perfectly too, so this can definitely be closed

**Comment by itagagaki** [comment]
Thanks for trying 2.1.0, and for reporting back!

This issue is now closed.
