### ISSUE TITLE
Moving Local Folders to top doesn't work

### ISSUE THREAD

**Issue by nclarius** [protz/Manually-Sort-Folders#147]
Setting Local Folders as default to move it to top takes no effect, the account remains at the bottom.

I am using the add-on in version 2.0.6 with Thunderbird 78.9.0 on Linux.

**Comment by Gluups** [comment]
Hello Natalie,
Choosing as default and putting on top are two different things.
You do the first with the "Advanced" tab : first tell you want to choose a particular folder rather than open the one opened during last session, and then choose it with the list on the right. If there is a sub-folder to select do not neglect it.
You do the second with the two first tabs, order the accounts and order the folders. These work together, I presume it will be clear when browsing through them.
For the accounts, you first select one and then depress the "up" and "down" (or equivalent, this is a translation) arrows to move it.
For the folders, you have three possible order methods to choose from, one of them lets you order manually the folders the same way as for the accounts.

**Comment by itagagaki** [comment]
The issue is probably a duplicate of #145.
If I remember correctly, it used to be possible to make a local folder the top, but not anymore.

Here is Jonathan's response to this issue.
https://github.com/protz/Manually-Sort-Folders/issues/114#issuecomment-654338307

**Comment by nclarius** [comment]
> The issue is probably a duplicate of #145.
> If I remember correctly, it used to be possible to make a local folder the top, but not anymore.
> 
> Here is Jonathan's response to this issue.
> [#114 (comment)](https://github.com/protz/Manually-Sort-Folders/issues/114#issuecomment-654338307)

Yes, it's the same issue.
