### ISSUE TITLE
Not working in Thunderbird 68.0

### ISSUE THREAD

**Issue by DavidBE-UK** [protz/Manually-Sort-Folders#86]
The extension is not working in Thunderbird 68.0 (now the available version to download from the Thunderbird site, now, though not yet being pushed to users as an update - I gather in part because many extensions don't yet work  in it). The add-ons manager in TB disables it as it is 'incompatible with Thunderbird 68.0'.

**Comment by email200202** [comment]
Same here.

**Comment by sHAsHiLx** [comment]
Yes, please update it to support latest stable release. Thanks!

**Comment by schneeschmelze** [comment]
+1. :(

Is there any chance to get the add-on into Thunderbird core?

**Comment by serenitatis** [comment]
Same for me =(

**Comment by Ximi1970** [comment]
Here you go...

https://github.com/Ximi1970/Manually-Sort-Folders/releases/tag/v2.0.0pre1

Merge request is submitted

**Comment by DavidBE-UK** [comment]
That's great and restores the function, so thanks. But ....

It only appears in the Menu Bar tools menu. I, like a lot of users, don't have the menu bar displaying, and use the Application Menu aka the 'hamburger menu', which is the default, I think. And especially now with 68.0 it is now a regular 'hamburger menu', not like the previous weird one. This extension should really also appear in the Application/hamburger menu Tools sub-menu (or the View sub-menu, perhaps).

With this extension only in the Menu Bar Tools menu, and the menu bar not displaying by default, I think a lot of users who install this may just think the extension is broken when they don't find it in the application/hamburger menu.

**Comment by Patryk27** [comment]
FWIW: in Thunderbird 68, you can open the old menu by pressing F10 and from there `Tools` -> `Manually sort folders`.

**Comment by pmboom18** [comment]
Ximi1970 link v2.0.0pre1 can be installed by dragging, but the account field is left blank. Therefore, it cannot be used. The close button does not move either.

**Comment by DavidBE-UK** [comment]
> FWIW: in Thunderbird 68, you can open the old menu by pressing F10 and from there `Tools` -> `Manually sort folders`.

And just pressing Alt shows the Menu Bar. But (a) I rarely use (or remember) keyboard shortcuts, and (b) as an extension usually only used occasionally, the thing is having to remember that it can't be accessed by 'normal' means, e.g. the Application menu where one expects to find things. I'm liable to remember only after a futile search in the Application menu.

Actually, one logical place a user might expect to find it is in the Folder Pane right-click context menu ... which extensions clearly can add themselves to as the ImportExportTools NG extension has added itself there.

**Comment by KOAR** [comment]
Hi, I'm really thankful that the Manually Sort Folders was developed. Obviously, some add-ons have stopped since the last update of Thunderbird. Including Manually Sort Folders. Me and certainly many other users would be grateful if you can make the AddOn fit again for the current Thunderbird version. Thanks!

**Comment by jpmorris** [comment]
@Ximi1970  that prerelease isn't working for me. All inputs are  blank in the manually  sort folders  window

**Comment by tooomm** [comment]
I saw a lot of extensions having their settings placed in "Hamburger Menu --> Addons --> *name of add-ons*"

Maybe that could be a place to put the options and config window, too.

**Comment by protz** [comment]
I took in @Ximi1970's pull request and fixed a couple more things, since I had the same symptoms as @jpmorris.

For the placement of the "manually sort folders" menu entry, I'll gladly take a pull request.

For the issue regarding Local Folders as default, the best I can suggest is filing a bug at https://bugzilla.mozilla.org and adding :protz in the CC field so that I can keep an eye on it.

Thanks for everyone's patience -- the new version should be approved shortly and in the meanwhile you can download https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201909221547.xpi and hit Tools > Add-ons > (cog menu) Install add-on from file.

Cheers,

Jonathan

**Comment by protz** [comment]
https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201909230901.xpi is a new version that also fixes the "choose startup folder" feature
